cd C:\Users\Hp\Downloads\webpage_data\website_05_01_2019
jemdoc.py index.jemdoc
jemdoc.py about.jemdoc
jemdoc.py academics.jemdoc
jemdoc.py aoi.jemdoc
jemdoc.py publications.jemdoc
jemdoc.py projects.jemdoc
jemdoc.py teaching.jemdoc
jemdoc.py readings.jemdoc
jemdoc.py groupphotos.jemdoc
jemdoc.py quotes.jemdoc
jemdoc.py links.jemdoc
jemdoc.py jemdocspage.jemdoc
jemdoc.py jemdocsmathjax.jemdoc
jemdoc.py createawebsite.jemdoc
jemdoc.py 5G.jemdoc
jemdoc.py philosophy.jemdoc
jemdoc.py Personal.jemdoc
jemdoc.py genealogy.jemdoc